blank_issues_enabled: false
contact_links:
  - name: Drivers Bot Channel
    url: https://t.me/DriversBotChannel
    about: Update Channel
  - name: Drivers Bot Channel
    url: https://t.me/DriversBotChannel
    about: Support Group
  - name: Drivers Bot Channel
    url: https://t.me/DriversBotChannel
    about: Bug Report & Feature Request Group
